server:
  port: 8088

spring:
  application:
    name: myflow

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myflow?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

