server:
  port: 8088
spring:
  application:
    name: flowable
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT&nullCatalogMeansCurrent=true
    username: root
    password: root
flowable:
  async-executor-activate: false
  database-schema-update: true
  process-definition-location-prefix: classpath*:/processes/

